STORY-6250: rename affiliate campaign relationship endpoint
Invoca/developer-docs pull request #188
Opened 2018-06-21 18:46 UTC by jebentier

After talking with Lauren, we like this name enough that we're going to backfill this name change to all previous versions.  I'll just cherrypick this commit to other versions when this is approved.

2018-06-21 20:33 UTC, nburwell requested changes
The new name is most likely the most common use case of this end point, but are we concerned that it doesn't cover the other use cases? 

By sending 'Suspended' (or 'Deactivated') you can bulk suspend all affiliate campaigns between this affiliate and advertiser.

--- 

I think we can also improve the intro paragraph to describe a bit what this does -- ie will: approve any existing affiliate campaigns (regardless of what status they were in before), and otherwise mark this affiliate as being auto-approved anytime they apply for a campaign with this advertiser in the future.

2018-06-21 20:33 UTC, nburwell commented on source/api_documentation/network_integration/advertiser_affiliate_relationships/index.rst
> +Auto-Approve Affilaite to Campaigns
typo in `Affiliate`

2018-06-21 20:33 UTC, nburwell commented on source/api_documentation/network_integration/index.rst
> +Auto-Approve Affilaite to Campaigns
typo in `Affiliate`

2018-06-21 20:57 UTC, jebentier commented on source/api_documentation/network_integration/advertiser_affiliate_relationships/index.rst
> +Auto-Approve Affilaite to Campaigns
done

2018-06-21 20:57 UTC, jebentier commented on source/api_documentation/network_integration/index.rst
> +Auto-Approve Affilaite to Campaigns
done

2018-06-21 20:59 UTC, jebentier commented
Lauren and I went back and forth on that with the name and Lauren decided that the name can be this, and that the description still indicates that you can approve or deny/other actions.  I can try taking a stab at the wording for the description, but we originally talked about only the title needing to be changed

2018-06-21 22:51 UTC, nburwell commented on source/api_documentation/network_integration/advertiser_affiliate_relationships/index.rst
> +When setting the Relationship between an Advertiser and Affiliate to Approved, all current and future campaign applications made between the Affiliate and Advertiser will be auto approved.
sorry small nit, didn't notice on slack:

You have `Auto-Approve` in the title, but use `auto approved` here in the sentence. Can we be consistent on both.

2018-06-22 16:33 UTC, jebentier commented on source/api_documentation/network_integration/advertiser_affiliate_relationships/index.rst
> +When setting the Relationship between an Advertiser and Affiliate to Approved, all current and future campaign applications made between the Affiliate and Advertiser will be auto approved.
done

2018-06-22 16:44 UTC, nburwell approved these changes

2018-06-22 16:58 UTC, caitlinrhd approved these changes
Looks good. Can you update the ticket title to reflect that we didn't end up hiding this page?

2018-06-22 17:08 UTC, jebentier commented
done

2018-06-22 17:15 UTC, merged