2019-02-01 Transactions API - for review (not to merge)
Invoca/developer-docs pull request #197
Opened 2019-02-05 01:19 UTC by nburwell

Here are the changes, based on the updated branch for 2018-11-01 version. 

**This is for review only and not to be merged.**

2019-02-05 16:01 UTC, alecjacobs5401 requested changes
This is so great, thanks for putting in this effort! Just have a few wording updates/value updates

I'll try and put together an updated set of documentation for SAPI too, just unsure how we're going to word it to not confuse any customers

2019-02-05 16:01 UTC, alecjacobs5401 commented on source/api_documentation/transactions_api/_custom_data_params.rst
> +1. (JSON & XML formats only) By including `custom_data` as field in the `include_columns` parameter (e.g. `include_columns=transaction_id,start_time_local,custom_data`) a nested structure is returned
Should we include the :greg_meyer: that partner names which include spaces will prevent XML format support?

2019-02-05 16:01 UTC, alecjacobs5401 commented on source/api_documentation/transactions_api/_custom_data_params.rst
> +    - One of: UserOverride, Api, Import, DynamicAttribution, LookupTable, Expression, Ivr, VirtualLine, AffiliateCampaign, AdvertiserCampaign, Affiliate, Advertiser, Network, Machine, Default, Syndic
Note to self: We should all a comment to the constants declaration for this that specifies we need to update this documentation on new additions for source

2019-02-05 16:01 UTC, alecjacobs5401 commented on source/api_documentation/transactions_api/_custom_data_params.rst
> +    - For data_type = Signal: 1 when true, 0 when false. For all other data types it is the string value of the field. Category and Short Text are up to 255 characters. Long Text can be up to 10,000
This is actually wrong for Signal values...we will format it to be `True` or `False` I believe. Do we want to keep the existing behavior of 1 and 0?

@vdinovi can you confirm?

2019-02-05 16:01 UTC, alecjacobs5401 commented on source/api_documentation/transactions_api/_custom_data_params.rst
> +    - One of: UserOverride, Api, Import, DynamicAttribution, LookupTable, Expression, Ivr, VirtualLine, AffiliateCampaign, AdvertiserCampaign, Affiliate, Advertiser, Network, Machine, Default, Syndic
`Machine` is also wrong..I believe we will run it through the formatter that turns it into `AI`. 

@vdinovi can you confirm?

2019-02-05 16:01 UTC, alecjacobs5401 commented on source/api_documentation/transactions_api/_intro.rst
> +    `$invoca_custom_source_columns` a dynamic constant that represents the sources for your current list of your Custom Data Fields. Note: If the list of custom columns changes, those changes will be
> for ~your~ **the** current list of your Custom Data Fields

to match above

2019-02-05 16:01 UTC, alecjacobs5401 commented on source/api_documentation/transactions_api/_signal_param_table.rst
> +    - The revenue applied to the call via Signal revenue proxies or Post Call Events.
thats an oof.

Thanks for fixing this.

2019-02-05 18:14 UTC, vdinovi commented on source/api_documentation/transactions_api/_custom_data_params.rst
> +1. (JSON & XML formats only) By including `custom_data` as field in the `include_columns` parameter (e.g. `include_columns=transaction_id,start_time_local,custom_data`) a nested structure is returned
:this:

2019-02-05 18:17 UTC, vdinovi commented on source/api_documentation/transactions_api/_custom_data_params.rst
> +    - One of: UserOverride, Api, Import, DynamicAttribution, LookupTable, Expression, Ivr, VirtualLine, AffiliateCampaign, AdvertiserCampaign, Affiliate, Advertiser, Network, Machine, Default, Syndic
We do this for the legacy signal source column but not yet for the new source columns. I can add this into the TX api behavior.

`unformatted.to_s.split(', ').map { |source| source == "Machine" ? "AI" : source }.sort.join(', ')`

2019-02-05 18:18 UTC, vdinovi commented on source/api_documentation/transactions_api/_custom_data_params.rst
> +    - For data_type = Signal: 1 when true, 0 when false. For all other data types it is the string value of the field. Category and Short Text are up to 255 characters. Long Text can be up to 10,000
So again a conflict between legacy signal columns and the newer custom data columns.

In legacy we format it to True/False, but in $invoca_custom_columns columns we use 1 or 0.

2019-02-05 18:27 UTC, nburwell commented on source/api_documentation/transactions_api/_custom_data_params.rst
> +    - One of: UserOverride, Api, Import, DynamicAttribution, LookupTable, Expression, Ivr, VirtualLine, AffiliateCampaign, AdvertiserCampaign, Affiliate, Advertiser, Network, Machine, Default, Syndic
We should match the legacy signal source column values.. can they share a reporting formatter so it stays in lock-step?

2019-02-05 18:29 UTC, nburwell commented on source/api_documentation/transactions_api/_custom_data_params.rst
> +    - For data_type = Signal: 1 when true, 0 when false. For all other data types it is the string value of the field. Category and Short Text are up to 255 characters. Long Text can be up to 10,000
Yeah I was assuming it was 1 or 0 still since `$invoca_custom_columns` already worked that way in production.. but I didn't realize we formatted the legacy signal column. 

For the new nested structure (of `custom_data`, using true/false/null would probably be preferred.. (Please don't change the behavior of the existing `$invoca_custom_columns` though)

2019-02-05 19:01 UTC, nburwell commented on source/api_documentation/transactions_api/_custom_data_params.rst
> +    - One of: UserOverride, Api, Import, DynamicAttribution, LookupTable, Expression, Ivr, VirtualLine, AffiliateCampaign, AdvertiserCampaign, Affiliate, Advertiser, Network, Machine, Default, Syndic
Updated docs to use `AI` here and in examples

2019-02-05 19:02 UTC, nburwell commented on source/api_documentation/transactions_api/_custom_data_params.rst
> +1. (JSON & XML formats only) By including `custom_data` as field in the `include_columns` parameter (e.g. `include_columns=transaction_id,start_time_local,custom_data`) a nested structure is returned
Added a GM caveat (put as part of the intro text that mentions what the fields are)

2019-02-05 19:02 UTC, nburwell commented on source/api_documentation/transactions_api/_custom_data_params.rst
> +    - For data_type = Signal: 1 when true, 0 when false. For all other data types it is the string value of the field. Category and Short Text are up to 255 characters. Long Text can be up to 10,000
Updated docs to use `true` / `false` in examples (for nested structure only)

2019-02-05 19:02 UTC, nburwell commented on source/api_documentation/transactions_api/_intro.rst
> +    `$invoca_custom_source_columns` a dynamic constant that represents the sources for your current list of your Custom Data Fields. Note: If the list of custom columns changes, those changes will be
Fixed

2019-02-05 19:03 UTC, nburwell commented
Ready for another review @alecjacobs5401

2019-02-05 19:36 UTC, vdinovi approved these changes

2019-02-05 21:09 UTC, alecjacobs5401 approved these changes

2019-02-05 21:09 UTC, alecjacobs5401 commented on source/api_documentation/transactions_api/_custom_data_params.rst
> +The Partner (API) Name is used as the field name returned by the Transactions API. Any Custom Data or Signal fields named the same as a standard Invoca Transactions API field will be returned by the
👍

2019-02-20 00:31 UTC, nburwell commented
Closing this PR as this branch is now the new default branch (being the latest version)

2019-02-20 00:31 UTC, closed without merging