STORY-11201: Add language_code for call ingestion API doc
Invoca/developer-docs pull request #286
Opened 2022-03-29 13:53 UTC by bebaek

[Adding language_code parameter doc for call ingestion API](https://invoca.atlassian.net/browse/STORY-11201)

## Checklist

- [ ] Find the [Service owning team](https://docs.google.com/spreadsheets/d/1YF2wuepY5SZTpVEdT9gwhTPhpnDGZeVjywEwvbJS5TQ/edit#gid=0&fvid=1520238175) for these changes, and tag the team as "Reviewers" on this PR
- [ ] Test the documentation changes on readthedocs as a private branch
- [ ] If changing general content, have agreement on whether to apply to latest version or all versions (if all versions, provide links to the related PRs below)

2022-03-31 13:51 UTC, ryanbales requested changes
Thanks for helping drive this forward @bebaek.  One small change.  Also, please be sure to refresh your branch. I had to push some recent fixes.

Thanks!

2022-03-31 13:51 UTC, ryanbales commented on source/api_documentation/call_ingestion_api/index.rst
> +    `language_code` The IETF language code for the call transcription. The supported codes are: `en-US`, `en-GB`, `es-ES`, `fr-FR`. This parameter can be processed only if `multiple_language_processi
@bebaek Can you reformat this section so it shows a table with the language code and language name.

For example:

- en-US: American English
- en-GB: British English
- etc...

I'm not sure if we have a likes of IEFTF tags in our documentation, but you can also look [here](https://en.wikipedia.org/wiki/IETF_language_tag).

2022-03-31 20:47 UTC, bebaek commented on source/api_documentation/call_ingestion_api/index.rst
> +    `language_code` The IETF language code for the call transcription. The supported codes are: `en-US`, `en-GB`, `es-ES`, `fr-FR`. This parameter can be processed only if `multiple_language_processi
Makes sense! I couldn't find good descriptions for "Spanish Spanish" and "French French" so I followed https://en.wikipedia.org/wiki/Language_localisation though.

2022-04-01 16:25 UTC, bebaek commented
Depends on: https://github.com/Invoca/web/pull/17716

2022-05-10 14:55 UTC, ryanbales approved these changes
Nice work @bebaek LGTM.  Ready to merge.  Please let me know if you need help getting this out to the docs site.

2022-05-17 19:51 UTC, merged