Update Invoca API token authentication help
Invoca/developer-docs pull request #325
Opened 2023-07-13 00:22 UTC by nburwell

Inspired by a question from Support (which came from a customer) on the calls In Progress API ([slack thread](https://invoca.slack.com/archives/C03UN2G58UV/p1689201061221149)) - the goal is to promote the best practice of sending our API token in a header, versus as a query param that is more likely to be logged in plaintext by some client logging (or server logging on our side).

* Consolidate the two pages that talk about using Invoca API tokens for auth
* Update the copy on the new, main page describing tokens and best practices
* Change all examples to use header based auth instead of passing token in the URL or body

I'm planning to only update the latest version versus all versions (as this is not a bug fix to any specific API endpoints).

## Checklist

- [ ] Find the [Service owning team](https://docs.google.com/spreadsheets/d/1YF2wuepY5SZTpVEdT9gwhTPhpnDGZeVjywEwvbJS5TQ/edit#gid=0&fvid=1520238175) for these changes, and tag the team as "Reviewers" on this PR
- [ ] Test the documentation changes on readthedocs as a private branch
- [ ] If changing general content, have agreement on whether to apply to latest version or all versions (if all versions, provide links to the related PRs below)

2023-07-13 00:59 UTC, nburwell commented
Test URL (must be signed into to ReadtheDocs)
https://developers.invoca.net/en/2022-08-01_update_auth_page/api_documentation/manage_api_credentials.html

2023-07-13 19:55 UTC, gmcgilvray requested changes
This all looks good! Verified added links work.
<img width="1332" alt="Screenshot 2023-07-13 at 12 54 44 PM" src="https://github.com/Invoca/developer-docs/assets/38059024/a244a5ee-a1ed-45a1-b242-bdb839c650da">

2023-07-13 21:27 UTC, gmcgilvray approved these changes

2023-07-14 06:27 UTC, ColinDKelley approved these changes
Thanks for improving the docs here!

2023-07-14 16:20 UTC, merged