Story 16566 create endpoint for deleting customer phone number
Invoca/developer-docs pull request #343
Opened 2023-10-26 18:34 UTC by SomeSayKosm

https://invoca.atlassian.net/browse/STORY-16566

## Checklist

- [ ] Find the [Service owning team](https://docs.google.com/spreadsheets/d/1YF2wuepY5SZTpVEdT9gwhTPhpnDGZeVjywEwvbJS5TQ/edit#gid=0&fvid=1520238175) for these changes, and tag the team as "Reviewers" on this PR
- [ ] Test the documentation changes on readthedocs as a private branch
- [ ] If changing general content, have agreement on whether to apply to latest version or all versions (if all versions, provide links to the related PRs below)

2023-10-26 19:34 UTC, abhig10 requested changes
I'll defer final approval until the time blocking PR's are merged. But until then, we can make the noted fixes.

2023-10-26 19:34 UTC, abhig10 commented on source/api_documentation/network_integration/ringpools/_delete_customer_phone_number.rst
> +    }
This is delete, so the response body should be `{}`.

2023-10-26 19:34 UTC, abhig10 commented on source/api_documentation/network_integration/ringpools/index.rst
> +   :page: customer_phone_number
Path and page is incorrect here. Also, we are calling them Destinations in documentation, unless we want to change it to Customer Phone Number.

```suggestion
   :path: /customer_phone_numbers/&lt;customer_phone_number_id&gt;
   :description: Delete a Destination
   :page: delete_customer_phone_number
```

2023-11-01 18:38 UTC, abhig10 requested changes
Just one change. Also, since I'm reverting the customer phone number documentation in https://github.com/Invoca/developer-docs/pull/345 and moving them to https://github.com/Invoca/developer-docs/pull/344, you should change the base in PR to `STORY-16669-add-2022-08-01-api-version-for-network-integration-and-add-related-documentation`

2023-11-01 18:38 UTC, abhig10 commented on source/api_documentation/network_integration/customer_phone_numbers/index.rst
> +   :page: delete_customer_phone_number
The path here is incorrect. It should have `customer_phone_numbers`. And also, add a blank line at the bottom.

```suggestion
   :path: /customer_phone_numbers/&lt;customer_phone_number_id&gt;
   :description: Delete a Destination
   :page: delete_customer_phone_number

```

2023-11-06 02:59 UTC, SomeSayKosm commented
Moving to https://github.com/Invoca/developer-docs/pull/347

2023-11-06 02:59 UTC, closed without merging