STORY-16952 Update API docs for whisper prompt condition
Invoca/developer-docs pull request #352
Opened 2023-12-13 18:16 UTC by abhig10

[STORY-16952 Update API docs for whisper prompt condition](https://invoca.atlassian.net/browse/STORY-16952)

Adds Invoca API documentation for setting the whisper_prompt_condition field on campaigns.

## Checklist

- [ ] Find the [Service owning team](https://docs.google.com/spreadsheets/d/1YF2wuepY5SZTpVEdT9gwhTPhpnDGZeVjywEwvbJS5TQ/edit#gid=0&fvid=1520238175) for these changes, and tag the team as "Reviewers" on this PR
- [ ] Test the documentation changes on readthedocs as a private branch
- [ ] If changing general content, have agreement on whether to apply to latest version or all versions (if all versions, provide links to the related PRs below)

2023-12-14 17:45 UTC, omeedrj requested changes
([CREG](https://github.com/erikthedeveloper/code-review-emoji-guide))

2023-12-14 17:45 UTC, omeedrj commented on source/api_documentation/network_integration/call_recording_and_whisper_prompt_conditions.rst
⛏️ I'd suggest renaming this file name to `ivr_tree_conditions` to match the `IvrTreeCondition` class that will be in web

2023-12-14 17:45 UTC, omeedrj commented on source/api_documentation/network_integration/call_recording_condition/index.rst
🔧 I'm leaving this comment here, but it applies more generally for STORY-16952 as a whole, given we're supporting API versions 2019-05-01+, we're also going to need branches for `2022-03-01` and `2020-10-01`. 

(I saw the [2022-08-01 PR](https://github.com/Invoca/developer-docs/pull/352) was created 👍)

![image](https://github.com/Invoca/developer-docs/assets/9993068/37d42e96-9d0c-4d82-ba21-a49f63c9443d)

2023-12-15 10:33 UTC, abhig10 commented on source/api_documentation/network_integration/call_recording_and_whisper_prompt_conditions.rst
Good point. Done.

2023-12-15 11:01 UTC, abhig10 commented on source/api_documentation/network_integration/call_recording_condition/index.rst
I remembered that I added support only for `2022-08-01` in https://github.com/Invoca/developer-docs/pull/344 without realizing that `2022-03-01` or `2020-10-01` also show documentation with `2019-05-01` API version. 🤦 

Creating PRs for `2022-03-01` and `2020-10-01`.

2023-12-15 12:41 UTC, abhig10 commented on source/api_documentation/network_integration/call_recording_condition/index.rst
PR for 2020-10-01 https://github.com/Invoca/developer-docs/pull/355
PR for 2022-03-01 https://github.com/Invoca/developer-docs/pull/354

2023-12-15 17:58 UTC, omeedrj approved these changes
I will coordinate merging this after Ringswitch has been deployed for [STORY-16951](https://invoca.atlassian.net/browse/STORY-16951)

2023-12-15 23:26 UTC, merged