STORY-18794: remove calls in progress update endpoint documentation
Invoca/developer-docs pull request #403
Opened 2024-07-11 18:32 UTC by jebentier

We're removing the documentation for the Call in Progress Update (PUT/POST) endpoint since we're going to be merging the functionality with the Signals API to keep the process of updating call information in Invoca simplified.

## Checklist

- [ ] Find the [Service owning team](https://docs.google.com/spreadsheets/d/1YF2wuepY5SZTpVEdT9gwhTPhpnDGZeVjywEwvbJS5TQ/edit#gid=0&fvid=1520238175) for these changes, and tag the team as "Reviewers" on this PR
- [ ] Test the documentation changes on readthedocs as a private branch
- [ ] If changing general content, have agreement on whether to apply to latest version or all versions (if all versions, provide links to the related PRs below)

2024-07-11 18:56 UTC, umarov approved these changes

2024-07-11 19:25 UTC, kamerynn approved these changes

2024-07-11 22:00 UTC, joroeinvoca requested changes

2024-07-11 22:00 UTC, joroeinvoca commented on source/api_documentation/calls_in_progress_api/index.rst
There's a reference to "set custom data values during a call" around line 12

2024-07-11 22:00 UTC, joroeinvoca commented on source/api_documentation/calls_in_progress_api/index.rst
Should we remove references to the `external_unique_id` field for now, especially since it says it can only be set by the Calls in Progress API? ~line 58

2024-07-11 22:00 UTC, joroeinvoca commented on source/api_documentation/calls_in_progress_api/index.rst
also mentioned here: https://github.com/Invoca/developer-docs/blob/ccc8b46a69992f6ea1313763264dba097eed07e8/source/api_documentation/calls_in_progress_api/_network_param_table.rst?plain=1#L94

2024-07-11 22:00 UTC, joroeinvoca commented on source/api_documentation/calls_in_progress_api/index.rst
Also shown in the API response examples, but perhaps that's fine for now since we specify that different users will see different fields depending on configuration.

2024-07-12 08:54 UTC, jebentier commented on source/api_documentation/calls_in_progress_api/index.rst
We're not changing what data is returned by the GET api, so we'll leave this alone.

2024-07-12 08:57 UTC, jebentier commented on source/api_documentation/calls_in_progress_api/index.rst
Done 4fa32e7a42941f2bbd892ab9219e36ee2b93efa3

2024-07-12 13:01 UTC, jebentier commented
I've addressed the verbiage concern, so going to go ahead and merge the changes to the documentation so they can be deployed. If there's any follow up comments/change please leave them here and I'll make sure to open a fast-follow PR to get them sorted.

2024-07-12 13:01 UTC, merged